user_dashboard/apps/main/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^signin$',views.signin,name="signin"),
    url(r'^register$',views.register,name="register"),
    url(r'^login$',views.login,name="login"),
    url(r'^logout$',views.logout,name="logout")
]

user_dashboard/apps/users/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^new$',views.new,name="new"),
    url(r'^create$',views.create,name="create"),
    url(r'^remove/(?P<id>\d+)$',views.destroy,name="remove"),
    url(r'^edit/(?P<id>\d+)$',views.edit,name="edit"),
    url(r'^show/(?P<id>\d+)$',views.show,name="show"),
    url(r'^update$',views.update,name="update"),
    url(r'^message$',views.message,name="message"),
    url(r'^comment$',views.comment,name="comment")
]

user_dashboard/user_dashboard/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.main.urls',namespace="index")),
    url(r'^users/',include('apps.users.urls',namespace="users")),
    url(r'^dashboard/',include('apps.dashboard.urls',namespace="dashboard")),
    url(r'^admin/', admin.site.urls),
]

user_dashboard/apps/main/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate, get_user
from django.contrib.auth.decorators import login_required
from ..users.forms import UserForm

# Create your views here.
def index(req):
    return render(req,"main/index.html")

def signin(req):
    return render(req,"main/signin.html")

def register(req):
    form = UserForm().as_p
    return render(req,"main/register.html", {"user_form": form })

def login(req):
    #get post info password, email
    user = authenticate(username=req.POST["username"],password=req.POST["password"])
    if user is not None:
        auth_login(req,user)
        return redirect(reverse("dashboard:index"))
    else:
        #user is not found
        messages.error(req,"User not found or Password Incorrect!")
        return redirect(reverse("index:signin"))

@login_required(login_url="index:signin")
def logout(req):
    #if a user is logged in or exists delete the session key
    user = get_user(req)
    auth_logout(req)
    return redirect(reverse("index:signin"))

user_dashboard/apps/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Test App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
            <a class="nav-item nav-link" href="{% url 'users:show' user.id  %}">Profile</a>
            <a class="nav-item nav-link justify-content-end" href="{% url 'index:logout' %}">Log Off</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'index:index' %}">Home</a>
            <a class="nav-item nav-link justify-content-end" href="{% url 'index:signin' %}"> Sign In</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

user_dashboard/apps/main/templates/main/index.html
{% extends "main/base.html" %}
{% block title %} Home Page {% endblock %}

{% block content %}
  <div class="jumbotron">
  <h1 class="display-4">Welcome to the Test</h1>
  <p class="lead">We're going to build a cool application using a MVC framework! This application was built with the Village88 folks!</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'index:register' %}" role="button">Start</a>
  </p>
  </div>
    <div class="row">
      <div class="col-md-4 col-sm-12">
        <h2>Manage Users</h2>
        <p>Using this application, you'll learn how to add, remove, and edit users for the application</p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2>Leave Messages</h2>
        <p>Users will be able to leave a message to another user using this application</p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2>Edit User Information</h2>
        <p>Admins will be able to edit another user's information (email address, first name, last name, etc)</p>
      </div>
    </div>
  </div>
{% endblock %}

user_dashboard/apps/main/templates/main/register.html
{% extends "main/base.html" %}
{% block title %} Register {% endblock %}
{% block content %}
<h1>Register</h1>
{% for message in messages %}
<p>{{ message }}</p>
{% endfor %}
{% include "users/register_form.html" %}
<p><a href="{% url 'index:signin' %}">Already have an account? Login</a></p>
{% endblock %}

user_dashboard/apps/main/templates/main/signin.html
{% extends "main/base.html" %}
{% block title %} Sign In Page {% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<p class="alert alert-primary">{{ message }}</p>
{% endfor %}
{% endif %}
<h3>Signin</h3>
<form action="{% url 'index:login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="username" name="username" id="username" required>
  <label for="password">Password: </label>
  <input type="password" name="password" id="password" required>
  <input type="submit" value="Sign In">
</form>
<p><a href="{% url 'index:register' %}">Don't have an account? Register.</a></p>
{% endblock %}